### ISSUE TITLE
update for Anki 2.1.42 please

### ISSUE THREAD

**Issue by omega3** [BlueBoxWare/AnkiResultCount#1]
```
Anki 2.1.42 (8eebfe18) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-22 16:46:05

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 36, in cmd
  File "aqt/webview.py", line 135, in _onCmd
  File "aqt/webview.py", line 580, in _onBridgeCmd
  File "aqt/toolbar.py", line 169, in _linkHandler
  File "aqt/toolbar.py", line 187, in _browseLinkHandler
  File "aqt/main.py", line 1067, in onBrowse
  File "aqt/__init__.py", line 101, in open
  File "aqt/browser.py", line 475, in __init__
  File "<decorator-gen-10>", line 2, in setupSearch
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 81, in repl
TypeError: initField() takes 1 positional argument but 3 were given
```

**Comment by BlueBoxWare** [comment]
It should work again.

**Comment by omega3** [comment]
I confirm it works. Thank you very much.

**Comment by BlueBoxWare** [comment]
Nice!
